on:
  push:
  pull_request:
  workflow_dispatch:
  

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v17
      uses: actions/setup-node@v1
      with:
        node-version: 17
    - name: install dependencies
      run: npm install
    - name: Build
      run: npm run build